name: viceversa
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  iconsax: ^0.0.8

  # Utility Packages
  http: ^1.2.2
  intl: ^0.20.1
  logger: ^2.5.0
  url_launcher: ^6.3.1

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  carousel_slider: ^5.0.0
  lucide_icons: ^0.257.0
  lottie: ^3.2.0
  connectivity_plus: ^6.1.1
  shimmer: ^3.0.0

  flutter_native_splash: any
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  readmore: ^3.0.0
  cached_network_image: ^3.4.1
  battery_plus: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/logos/
    - assets/images/
    - assets/images/welcome/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/categories/
    - assets/images/products/

  # Fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
